version: "3.7"
services:
    odoo:
        image: odoo:13.0
        platform: linux/amd64
        container_name: mi_contenedor_odoo
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres10
            - USER=odoo
            - PASSWORD=odoo
    postgresql:
        image: postgres:10
        container_name: postgres10_botella
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
